<?php

return [
    'surahs' => [
        1 => ['arabic' => 'الفاتحة', 'transliteration' => 'Al-Fatihah', 'english' => 'The Opening'],
        2 => ['arabic' => 'البقرة', 'transliteration' => 'Al-Baqarah', 'english' => 'The Cow'],
        3 => ['arabic' => 'آل عمران', 'transliteration' => 'Ali Imran', 'english' => 'Family of Imran'],
        4 => ['arabic' => 'النساء', 'transliteration' => 'An-Nisa', 'english' => 'The Women'],
        5 => ['arabic' => 'المائدة', 'transliteration' => 'Al-Ma\'idah', 'english' => 'The Table Spread'],
        6 => ['arabic' => 'الأنعام', 'transliteration' => 'Al-An\'am', 'english' => 'The Cattle'],
        7 => ['arabic' => 'الأعراف', 'transliteration' => 'Al-A\'raf', 'english' => 'The Heights'],
        8 => ['arabic' => 'الأنفال', 'transliteration' => 'Al-Anfal', 'english' => 'The Spoils of War'],
        9 => ['arabic' => 'التوبة', 'transliteration' => 'At-Tawbah', 'english' => 'The Repentance'],
        10 => ['arabic' => 'يونس', 'transliteration' => 'Yunus', 'english' => 'Jonah'],
        11 => ['arabic' => 'هود', 'transliteration' => 'Hud', 'english' => 'Hud'],
        12 => ['arabic' => 'يوسف', 'transliteration' => 'Yusuf', 'english' => 'Joseph'],
        13 => ['arabic' => 'الرعد', 'transliteration' => 'Ar-Ra\'d', 'english' => 'The Thunder'],
        14 => ['arabic' => 'إبراهيم', 'transliteration' => 'Ibrahim', 'english' => 'Abraham'],
        15 => ['arabic' => 'الحجر', 'transliteration' => 'Al-Hijr', 'english' => 'The Rocky Tract'],
        16 => ['arabic' => 'النحل', 'transliteration' => 'An-Nahl', 'english' => 'The Bee'],
        17 => ['arabic' => 'الإسراء', 'transliteration' => 'Al-Isra', 'english' => 'The Night Journey'],
        18 => ['arabic' => 'الكهف', 'transliteration' => 'Al-Kahf', 'english' => 'The Cave'],
        19 => ['arabic' => 'مريم', 'transliteration' => 'Maryam', 'english' => 'Mary'],
        20 => ['arabic' => 'طه', 'transliteration' => 'Ta-Ha', 'english' => 'Ta-Ha'],
        21 => ['arabic' => 'الأنبياء', 'transliteration' => 'Al-Anbiya', 'english' => 'The Prophets'],
        22 => ['arabic' => 'الحج', 'transliteration' => 'Al-Hajj', 'english' => 'The Pilgrimage'],
        23 => ['arabic' => 'المؤمنون', 'transliteration' => 'Al-Mu\'minun', 'english' => 'The Believers'],
        24 => ['arabic' => 'النور', 'transliteration' => 'An-Nur', 'english' => 'The Light'],
        25 => ['arabic' => 'الفرقان', 'transliteration' => 'Al-Furqan', 'english' => 'The Criterion'],
        26 => ['arabic' => 'الشعراء', 'transliteration' => 'Ash-Shu\'ara', 'english' => 'The Poets'],
        27 => ['arabic' => 'النمل', 'transliteration' => 'An-Naml', 'english' => 'The Ant'],
        28 => ['arabic' => 'القصص', 'transliteration' => 'Al-Qasas', 'english' => 'The Stories'],
        29 => ['arabic' => 'العنكبوت', 'transliteration' => 'Al-Ankabut', 'english' => 'The Spider'],
        30 => ['arabic' => 'الروم', 'transliteration' => 'Ar-Rum', 'english' => 'The Romans'],
        31 => ['arabic' => 'لقمان', 'transliteration' => 'Luqman', 'english' => 'Luqman'],
        32 => ['arabic' => 'السجدة', 'transliteration' => 'As-Sajdah', 'english' => 'The Prostration'],
        33 => ['arabic' => 'الأحزاب', 'transliteration' => 'Al-Ahzab', 'english' => 'The Combined Forces'],
        34 => ['arabic' => 'سبأ', 'transliteration' => 'Saba', 'english' => 'Sheba'],
        35 => ['arabic' => 'فاطر', 'transliteration' => 'Fatir', 'english' => 'Originator'],
        36 => ['arabic' => 'يس', 'transliteration' => 'Ya-Sin', 'english' => 'Ya-Sin'],
        37 => ['arabic' => 'الصافات', 'transliteration' => 'As-Saffat', 'english' => 'Those Who Set the Ranks'],
        38 => ['arabic' => 'ص', 'transliteration' => 'Sad', 'english' => 'Sad'],
        39 => ['arabic' => 'الزمر', 'transliteration' => 'Az-Zumar', 'english' => 'The Groups'],
        40 => ['arabic' => 'غافر', 'transliteration' => 'Ghafir', 'english' => 'The Forgiver'],
        41 => ['arabic' => 'فصلت', 'transliteration' => 'Fussilat', 'english' => 'Explained in Detail'],
        42 => ['arabic' => 'الشورى', 'transliteration' => 'Ash-Shura', 'english' => 'The Consultation'],
        43 => ['arabic' => 'الزخرف', 'transliteration' => 'Az-Zukhruf', 'english' => 'The Ornaments of Gold'],
        44 => ['arabic' => 'الدخان', 'transliteration' => 'Ad-Dukhan', 'english' => 'The Smoke'],
        45 => ['arabic' => 'الجاثية', 'transliteration' => 'Al-Jathiyah', 'english' => 'The Kneeling'],
        46 => ['arabic' => 'الأحقاف', 'transliteration' => 'Al-Ahqaf', 'english' => 'The Wind-Curved Sandhills'],
        47 => ['arabic' => 'محمد', 'transliteration' => 'Muhammad', 'english' => 'Muhammad'],
        48 => ['arabic' => 'الفتح', 'transliteration' => 'Al-Fath', 'english' => 'The Victory'],
        49 => ['arabic' => 'الحجرات', 'transliteration' => 'Al-Hujurat', 'english' => 'The Rooms'],
        50 => ['arabic' => 'ق', 'transliteration' => 'Qaf', 'english' => 'Qaf'],
        51 => ['arabic' => 'الذاريات', 'transliteration' => 'Adh-Dhariyat', 'english' => 'The Winnowing Winds'],
        52 => ['arabic' => 'الطور', 'transliteration' => 'At-Tur', 'english' => 'The Mount'],
        53 => ['arabic' => 'النجم', 'transliteration' => 'An-Najm', 'english' => 'The Star'],
        54 => ['arabic' => 'القمر', 'transliteration' => 'Al-Qamar', 'english' => 'The Moon'],
        55 => ['arabic' => 'الرحمن', 'transliteration' => 'Ar-Rahman', 'english' => 'The Most Merciful'],
        56 => ['arabic' => 'الواقعة', 'transliteration' => 'Al-Waqi\'ah', 'english' => 'The Inevitable'],
        57 => ['arabic' => 'الحديد', 'transliteration' => 'Al-Hadid', 'english' => 'The Iron'],
        58 => ['arabic' => 'المجادلة', 'transliteration' => 'Al-Mujadilah', 'english' => 'The Pleading Woman'],
        59 => ['arabic' => 'الحشر', 'transliteration' => 'Al-Hashr', 'english' => 'The Exile'],
        60 => ['arabic' => 'الممتحنة', 'transliteration' => 'Al-Mumtahanah', 'english' => 'She Who Is to Be Examined'],
        61 => ['arabic' => 'الصف', 'transliteration' => 'As-Saff', 'english' => 'The Ranks'],
        62 => ['arabic' => 'الجمعة', 'transliteration' => 'Al-Jumu\'ah', 'english' => 'The Congregation'],
        63 => ['arabic' => 'المنافقون', 'transliteration' => 'Al-Munafiqun', 'english' => 'The Hypocrites'],
        64 => ['arabic' => 'التغابن', 'transliteration' => 'At-Taghabun', 'english' => 'Mutual Disillusion'],
        65 => ['arabic' => 'الطلاق', 'transliteration' => 'At-Talaq', 'english' => 'The Divorce'],
        66 => ['arabic' => 'التحريم', 'transliteration' => 'At-Tahrim', 'english' => 'The Prohibition'],
        67 => ['arabic' => 'الملك', 'transliteration' => 'Al-Mulk', 'english' => 'The Sovereignty'],
        68 => ['arabic' => 'القلم', 'transliteration' => 'Al-Qalam', 'english' => 'The Pen'],
        69 => ['arabic' => 'الحاقة', 'transliteration' => 'Al-Haqqah', 'english' => 'The Reality'],
        70 => ['arabic' => 'المعارج', 'transliteration' => 'Al-Ma\'arij', 'english' => 'The Ascending Stairways'],
        71 => ['arabic' => 'نوح', 'transliteration' => 'Nuh', 'english' => 'Noah'],
        72 => ['arabic' => 'الجن', 'transliteration' => 'Al-Jinn', 'english' => 'The Jinn'],
        73 => ['arabic' => 'المزمل', 'transliteration' => 'Al-Muzzammil', 'english' => 'The Enshrouded One'],
        74 => ['arabic' => 'المدثر', 'transliteration' => 'Al-Muddaththir', 'english' => 'The Cloaked One'],
        75 => ['arabic' => 'القيامة', 'transliteration' => 'Al-Qiyamah', 'english' => 'The Resurrection'],
        76 => ['arabic' => 'الإنسان', 'transliteration' => 'Al-Insan', 'english' => 'The Human'],
        77 => ['arabic' => 'المرسلات', 'transliteration' => 'Al-Mursalat', 'english' => 'Those Sent Forth'],
        78 => ['arabic' => 'النبأ', 'transliteration' => 'An-Naba', 'english' => 'The Tidings'],
        79 => ['arabic' => 'النازعات', 'transliteration' => 'An-Nazi\'at', 'english' => 'Those Who Drag Forth'],
        80 => ['arabic' => 'عبس', 'transliteration' => 'Abasa', 'english' => 'He Frowned'],
        81 => ['arabic' => 'التكوير', 'transliteration' => 'At-Takwir', 'english' => 'The Overthrowing'],
        82 => ['arabic' => 'الإنفطار', 'transliteration' => 'Al-Infitar', 'english' => 'The Cleaving'],
        83 => ['arabic' => 'المطففين', 'transliteration' => 'Al-Mutaffifin', 'english' => 'Defrauding'],
        84 => ['arabic' => 'الإنشقاق', 'transliteration' => 'Al-Inshiqaq', 'english' => 'The Splitting Open'],
        85 => ['arabic' => 'البروج', 'transliteration' => 'Al-Buruj', 'english' => 'The Mansions of the Stars'],
        86 => ['arabic' => 'الطارق', 'transliteration' => 'At-Tariq', 'english' => 'The Nightcomer'],
        87 => ['arabic' => 'الأعلى', 'transliteration' => 'Al-A\'la', 'english' => 'The Most High'],
        88 => ['arabic' => 'الغاشية', 'transliteration' => 'Al-Ghashiyah', 'english' => 'The Overwhelming'],
        89 => ['arabic' => 'الفجر', 'transliteration' => 'Al-Fajr', 'english' => 'The Dawn'],
        90 => ['arabic' => 'البلد', 'transliteration' => 'Al-Balad', 'english' => 'The City'],
        91 => ['arabic' => 'الشمس', 'transliteration' => 'Ash-Shams', 'english' => 'The Sun'],
        92 => ['arabic' => 'الليل', 'transliteration' => 'Al-Layl', 'english' => 'The Night'],
        93 => ['arabic' => 'الضحى', 'transliteration' => 'Ad-Duha', 'english' => 'The Morning Brightness'],
        94 => ['arabic' => 'الشرح', 'transliteration' => 'Ash-Sharh', 'english' => 'The Relief'],
        95 => ['arabic' => 'التين', 'transliteration' => 'At-Tin', 'english' => 'The Fig'],
        96 => ['arabic' => 'العلق', 'transliteration' => 'Al-\'Alaq', 'english' => 'The Clot'],
        97 => ['arabic' => 'القدر', 'transliteration' => 'Al-Qadr', 'english' => 'The Power'],
        98 => ['arabic' => 'البينة', 'transliteration' => 'Al-Bayyinah', 'english' => 'The Clear Proof'],
        99 => ['arabic' => 'الزلزلة', 'transliteration' => 'Az-Zalzalah', 'english' => 'The Earthquake'],
        100 => ['arabic' => 'العاديات', 'transliteration' => 'Al-\'Adiyat', 'english' => 'The Courser'],
        101 => ['arabic' => 'القارعة', 'transliteration' => 'Al-Qari\'ah', 'english' => 'The Calamity'],
        102 => ['arabic' => 'التكاثر', 'transliteration' => 'At-Takathur', 'english' => 'The Rivalry in World Increase'],
        103 => ['arabic' => 'العصر', 'transliteration' => 'Al-\'Asr', 'english' => 'The Declining Day'],
        104 => ['arabic' => 'الهمزة', 'transliteration' => 'Al-Humazah', 'english' => 'The Traducer'],
        105 => ['arabic' => 'الفيل', 'transliteration' => 'Al-Fil', 'english' => 'The Elephant'],
        106 => ['arabic' => 'قريش', 'transliteration' => 'Quraysh', 'english' => 'Quraysh'],
        107 => ['arabic' => 'الماعون', 'transliteration' => 'Al-Ma\'un', 'english' => 'The Small Kindnesses'],
        108 => ['arabic' => 'الكوثر', 'transliteration' => 'Al-Kawthar', 'english' => 'The Abundance'],
        109 => ['arabic' => 'الكافرون', 'transliteration' => 'Al-Kafirun', 'english' => 'The Disbelievers'],
        110 => ['arabic' => 'النصر', 'transliteration' => 'An-Nasr', 'english' => 'The Divine Support'],
        111 => ['arabic' => 'المسد', 'transliteration' => 'Al-Masad', 'english' => 'The Palm Fiber'],
        112 => ['arabic' => 'الإخلاص', 'transliteration' => 'Al-Ikhlas', 'english' => 'The Sincerity'],
        113 => ['arabic' => 'الفلق', 'transliteration' => 'Al-Falaq', 'english' => 'The Daybreak'],
        114 => ['arabic' => 'الناس', 'transliteration' => 'An-Nas', 'english' => 'Mankind'],
    ],
];
